# fly.toml file generated for restless-wind-9882 on 2023-01-17T00:12:59-05:00

app = "restless-wind-9882"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8080
  MONGO_URI = 'mongodb+srv://masterdufel:khyzosb2CXsCL79p@cluster0.koihrij.mongodb.net/phonebook?retryWrites=true&w=majority'

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
